apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: recipe-discovery:latest
          ports:
            - containerPort: 8080
          env:
            - name: ELASTICSEARCH_HOST
              value: localhost
            - name: ELASTICSEARCH_PORT
              value: 9200
          # Add additional environment variables if needed
      # Add volume mounts, secrets, and other configurations if needed
