version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      es:
        condition: service_healthy
    restart: on-failure
    networks:
      - net
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - net
    healthcheck:
      test: curl -s http://es:9200/_cluster/health?wait_for_status=green&timeout=1s >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50

networks:
  net:
    driver: bridge
